//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiristorModule.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public ushort CurrentKz1 {
            get {
                return ((ushort)(this["CurrentKz1"]));
            }
            set {
                this["CurrentKz1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public ushort CurrentKz2 {
            get {
                return ((ushort)(this["CurrentKz2"]));
            }
            set {
                this["CurrentKz2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public byte PersentTestPower {
            get {
                return ((byte)(this["PersentTestPower"]));
            }
            set {
                this["PersentTestPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte NumberOfTest {
            get {
                return ((byte)(this["NumberOfTest"]));
            }
            set {
                this["NumberOfTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54")]
        public int NominalTok1sk {
            get {
                return ((int)(this["NominalTok1sk"]));
            }
            set {
                this["NominalTok1sk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte VremiaKzMs1 {
            get {
                return ((byte)(this["VremiaKzMs1"]));
            }
            set {
                this["VremiaKzMs1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte VremiaKzMs2 {
            get {
                return ((byte)(this["VremiaKzMs2"]));
            }
            set {
                this["VremiaKzMs2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte AddressMaster {
            get {
                return ((byte)(this["AddressMaster"]));
            }
            set {
                this["AddressMaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("103")]
        public byte AddressSlave {
            get {
                return ((byte)(this["AddressSlave"]));
            }
            set {
                this["AddressSlave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>5</string>
  <string>7</string>
  <string>9</string>
  <string>11</string>
  <string>13</string>
  <string>15</string>
  <string>17</string>
  <string>19</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Time {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Time"]));
            }
            set {
                this["Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>40</string>
  <string>30</string>
  <string>40</string>
  <string>50</string>
  <string>60</string>
  <string>70</string>
  <string>80</string>
  <string>90</string>
  <string>100</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Capacity {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Capacity"]));
            }
            set {
                this["Capacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>COM1</string>
  <string>COM2</string>
  <string>COM3</string>
  <string>COM4</string>
  <string>COM5</string>
  <string>COM6</string>
  <string>COM7</string>
  <string>COM8</string>
  <string>COM9</string>
  <string>COM10</string>
  <string>COM11</string>
  <string>COM12</string>
  <string>COM13</string>
  <string>COM14</string>
  <string>COM15</string>
  <string>COM16</string>
  <string>COM17</string>
  <string>COM18</string>
  <string>COM19</string>
  <string>COM20</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PortNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PortNames"]));
            }
            set {
                this["PortNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>1</string>\r\n  <string>2</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StopBits {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StopBits"]));
            }
            set {
                this["StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>7</string>\r\n  <string>8</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DataBits {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DataBits"]));
            }
            set {
                this["DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>300</string>
  <string>600</string>
  <string>1200</string>
  <string>2400</string>
  <string>4800</string>
  <string>9600</string>
  <string>14400</string>
  <string>19200</string>
  <string>38400</string>
  <string>56000</string>
  <string>57600</string>
  <string>115200</string>
  <string>128000</string>
  <string>230400</string>
  <string>256000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BaudRates {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BaudRates"]));
            }
            set {
                this["BaudRates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string PortName {
            get {
                return ((string)(this["PortName"]));
            }
            set {
                this["PortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string StopBit {
            get {
                return ((string)(this["StopBit"]));
            }
            set {
                this["StopBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string BaudRate {
            get {
                return ((string)(this["BaudRate"]));
            }
            set {
                this["BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Нет проверки")]
        public string Parity {
            get {
                return ((string)(this["Parity"]));
            }
            set {
                this["Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string DataBit {
            get {
                return ((string)(this["DataBit"]));
            }
            set {
                this["DataBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Нет проверки</string>
  <string>Четный</string>
  <string>Нечетный</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Parities {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Parities"]));
            }
            set {
                this["Parities"] = value;
            }
        }
    }
}
